/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static sql.CustomerFirstFrame.UserFFIDF;
/**
 *
 * @author escan
 */
public class Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    public Customers() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }

    public void date() {
        
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(year + "/" + (month + 1) + "/" + day);
        
    }
    
    public void time() {
        
        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        time.setText(hour + ":" + minute + ":" + second);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        UPasswordF = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        UViewBTNInM = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UAddressF = new javax.swing.JTextField();
        UIDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        UPhoneNoF = new javax.swing.JTextField();
        UERICodeF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UDOBLYear = new javax.swing.JTextField();
        UMonthDOBF = new javax.swing.JTextField();
        UDayDOBF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        YearEXPDate = new javax.swing.JTextField();
        MonthUserEXPDateF = new javax.swing.JTextField();
        DayEXPDateUserF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UCardNOF = new javax.swing.JTextField();
        UDOFL = new javax.swing.JLabel();
        UCardEXPDateL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UCCVBankCardF = new javax.swing.JTextField();
        UserNameF = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        LiveViewCBTN = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        VSID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/men.png"))); // NOI18N
        jPanel6.add(jLabel21);
        jLabel21.setBounds(120, 150, 500, 350);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newImages/logout.png"))); // NOI18N
        jButton1.setText("Logout ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(300, 560, 110, 50);

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton12.setText("Un-register me ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jButton12.setBounds(420, 559, 180, 50);

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/folder.png"))); // NOI18N
        jButton10.setText("Important info");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(130, 559, 160, 50);

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/2910857.jpg"))); // NOI18N
        jPanel6.add(jLabel24);
        jLabel24.setBounds(-10, 0, 740, 770);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("LOG-OUT", jPanel1);

        jPanel7.setLayout(null);

        UPasswordF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UPasswordFKeyPressed(evt);
            }
        });
        jPanel7.add(UPasswordF);
        UPasswordF.setBounds(160, 100, 210, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("YOUR-PASSWORD");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(50, 100, 105, 30);

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton11.setText("CLEAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);
        jButton11.setBounds(460, 640, 110, 39);

        UViewBTNInM.setBackground(new java.awt.Color(51, 51, 51));
        UViewBTNInM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UViewBTNInM.setForeground(new java.awt.Color(255, 255, 255));
        UViewBTNInM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        UViewBTNInM.setText("VIEW");
        UViewBTNInM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UViewBTNInMActionPerformed(evt);
            }
        });
        jPanel7.add(UViewBTNInM);
        UViewBTNInM.setBounds(340, 640, 110, 39);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("PHONE-NUMBER");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(60, 250, 96, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        jButton2.setText("UP-DATE");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);
        jButton2.setBounds(577, 640, 130, 39);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ERI-CODE");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(430, 250, 54, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("YOUR-ADDRESS");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(390, 180, 92, 30);

        UAddressF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UAddressFKeyPressed(evt);
            }
        });
        jPanel7.add(UAddressF);
        UAddressF.setBounds(490, 180, 200, 30);

        UIDF.setEditable(false);
        UIDF.setBackground(new java.awt.Color(204, 204, 204));
        UIDF.setText("CLICK ME TO VIEW YOOUR ID");
        UIDF.setToolTipText("Click me to view your ID");
        UIDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UIDFMouseClicked(evt);
            }
        });
        jPanel7.add(UIDF);
        UIDF.setBounds(490, 100, 200, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("YOUR-ID");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(430, 100, 51, 30);

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("SHOW-PASSWORD?");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton1);
        jToggleButton1.setBounds(10, 60, 144, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Password is hidden for security reasons");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(160, 60, 216, 30);

        UPhoneNoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPhoneNoFActionPerformed(evt);
            }
        });
        UPhoneNoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UPhoneNoFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UPhoneNoFKeyTyped(evt);
            }
        });
        jPanel7.add(UPhoneNoF);
        UPhoneNoF.setBounds(160, 250, 210, 30);

        UERICodeF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UERICodeFKeyPressed(evt);
            }
        });
        jPanel7.add(UERICodeF);
        UERICodeF.setBounds(490, 250, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("YOUR-DOB");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(410, 370, 64, 30);

        UDOBLYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDOBLYearActionPerformed(evt);
            }
        });
        UDOBLYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UDOBLYearKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UDOBLYearKeyTyped(evt);
            }
        });
        jPanel7.add(UDOBLYear);
        UDOBLYear.setBounds(480, 370, 64, 30);

        UMonthDOBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMonthDOBFActionPerformed(evt);
            }
        });
        UMonthDOBF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMonthDOBFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UMonthDOBFKeyTyped(evt);
            }
        });
        jPanel7.add(UMonthDOBF);
        UMonthDOBF.setBounds(550, 370, 64, 30);

        UDayDOBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDayDOBFActionPerformed(evt);
            }
        });
        UDayDOBF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UDayDOBFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UDayDOBFKeyTyped(evt);
            }
        });
        jPanel7.add(UDayDOBF);
        UDayDOBF.setBounds(620, 370, 64, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("CARD EXP DATE");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(380, 520, 89, 30);

        YearEXPDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearEXPDateActionPerformed(evt);
            }
        });
        YearEXPDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YearEXPDateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YearEXPDateKeyTyped(evt);
            }
        });
        jPanel7.add(YearEXPDate);
        YearEXPDate.setBounds(480, 520, 64, 30);

        MonthUserEXPDateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthUserEXPDateFActionPerformed(evt);
            }
        });
        MonthUserEXPDateF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MonthUserEXPDateFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MonthUserEXPDateFKeyTyped(evt);
            }
        });
        jPanel7.add(MonthUserEXPDateF);
        MonthUserEXPDateF.setBounds(550, 520, 64, 30);

        DayEXPDateUserF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayEXPDateUserFActionPerformed(evt);
            }
        });
        DayEXPDateUserF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DayEXPDateUserFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DayEXPDateUserFKeyTyped(evt);
            }
        });
        jPanel7.add(DayEXPDateUserF);
        DayEXPDateUserF.setBounds(620, 520, 64, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("BANK CARD NUMBER");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(30, 440, 122, 30);

        UCardNOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCardNOFActionPerformed(evt);
            }
        });
        UCardNOF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UCardNOFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UCardNOFKeyTyped(evt);
            }
        });
        jPanel7.add(UCardNOF);
        UCardNOF.setBounds(160, 440, 210, 30);

        UDOFL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UDOFL.setForeground(new java.awt.Color(153, 153, 153));
        UDOFL.setText("YYYY-MM-DD");
        jPanel7.add(UDOFL);
        UDOFL.setBounds(480, 480, 78, 30);

        UCardEXPDateL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UCardEXPDateL.setForeground(new java.awt.Color(153, 153, 153));
        UCardEXPDateL.setText("YYYY-MM-DD");
        jPanel7.add(UCardEXPDateL);
        UCardEXPDateL.setBounds(480, 340, 78, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("YOUR-NAME");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(80, 180, 72, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("BANK CARD CCV NUMBER");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(10, 520, 147, 30);

        UCCVBankCardF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCCVBankCardFActionPerformed(evt);
            }
        });
        UCCVBankCardF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UCCVBankCardFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UCCVBankCardFKeyTyped(evt);
            }
        });
        jPanel7.add(UCCVBankCardF);
        UCCVBankCardF.setBounds(160, 520, 210, 30);

        UserNameF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserNameFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserNameFKeyTyped(evt);
            }
        });
        jPanel7.add(UserNameF);
        UserNameF.setBounds(160, 180, 210, 30);

        jToggleButton2.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/DOT.gif"))); // NOI18N
        jToggleButton2.setText("Dark-Mode");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jToggleButton2);
        jToggleButton2.setBounds(560, 20, 130, 40);

        jLabel16.setText("Attention: Numbers only!");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(20, 10, 150, 30);
        jLabel16.setVisible(false);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testingpackage/wp9021900.jpg"))); // NOI18N
        jPanel7.add(jLabel26);
        jLabel26.setBounds(0, 0, 750, 730);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("MANAGE", jPanel2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("ALL THE VEHICLES IN STORE ARE DISPLAYED HERE.");

        LiveViewCBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        LiveViewCBTN.setText("LIVE-VIEW");
        LiveViewCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiveViewCBTNActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/w.png"))); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 445, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(LiveViewCBTN)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LiveViewCBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("VIEW", jPanel3);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        jButton5.setText("SEND");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel20.setText("If you are having difficulties in the APP, our team will contact you to to put you back on the track!");

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        jButton13.setText("Read FAQ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Fixed3.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton13)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane3.addTab("HELP", jPanel4);

        VSID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VSIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VSIDKeyTyped(evt);
            }
        });

        jLabel10.setText("Vehicle-ID");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        jButton6.setText("Search-Vehicle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        jButton7.setText("Purchase");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/folder.png"))); // NOI18N
        jButton9.setText("Logout");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setText("Digits only!");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAESRESOURCES/explode-truck.gif"))); // NOI18N

        jLabel23.setText("Purchase your dream vehicle!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(VSID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addContainerGap())))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("PURCHASE", jPanel5);

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        JOptionPane.showMessageDialog(null, "You have logged out successfully!");
        System.exit(0);
        
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        SQL.update ();
        
    }                                        

    private void LiveViewCBTNActionPerformed(java.awt.event.ActionEvent evt) {                                             

        LiveViewCBTN.setText("Refresh");
       
        SQL.view ();
        
    }                                            

    private void UIDFMouseClicked(java.awt.event.MouseEvent evt) {                                  
       
        Customers.UIDF.setText(CustomerFirstFrame.UserFFIDF.getText());
        
    }                                 

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        SQL.HelpBTNForCustomers ();
        
    }                                        

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {                                        
       
        jTextArea1.setEditable(false);
        
    }                                       

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        SQL.viewforCustomers();
        
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        jTextArea3.setText(null);
        
    }                                        

    private void jTextArea3MouseClicked(java.awt.event.MouseEvent evt) {                                        
        
        jTextArea3.setEditable(false);
        
    }                                       

    private void UViewBTNInMActionPerformed(java.awt.event.ActionEvent evt) {                                            

        SQL.viewCustomerDetails();
        
    }                                           

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       
        SQL.ClearCustomerFields();
        
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          

        this.dispose();
        
        int X = JOptionPane.showConfirmDialog(null, "Attention! You are going to delete your data from our DB\n"
                + "Click you to confirm","DB-Response", JOptionPane.YES_NO_OPTION);
        
        if (X == 0) {
            
            SQL.deleteUser();
            this.dispose();
            
        }
        
        else {
            
            Customers.main(null);
        }
    }                                         

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               

        SQL.ToggleBTNForPassWord();
        
    }                                              

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        JOptionPane.showMessageDialog(null, "You have logged out successfully!");
        System.exit(0);
        
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        CustomerPurchaseConfirmation.main(null);
        
    }                                        

    private void UDOBLYearActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                         

    private void UMonthDOBFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                          

    private void UDayDOBFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                        

    private void YearEXPDateActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                           

    private void MonthUserEXPDateFActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                                 

    private void DayEXPDateUserFActionPerformed(java.awt.event.ActionEvent evt) {                                                
       
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                               

    private void UDOBLYearKeyPressed(java.awt.event.KeyEvent evt) {                                     
        
        int lengthPIN = UDOBLYear.getText().length();
        
        if (lengthPIN == 4 ) {
            
            UDOBLYear.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 4 digits");
            
        }
    }                                    

    private void UMonthDOBFKeyPressed(java.awt.event.KeyEvent evt) {                                      
        
        int lengthPIN = UMonthDOBF.getText().length();
        
        if (lengthPIN == 2 ) {
            
            UMonthDOBF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 2 digits");
            
        }
        
    }                                     

    private void UDayDOBFKeyPressed(java.awt.event.KeyEvent evt) {                                    
        
        int lengthPIN = UDayDOBF.getText().length();
        
        if (lengthPIN == 2 ) {
            
            UDayDOBF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 2 digits");
            
        }
        
    }                                   

    private void YearEXPDateKeyPressed(java.awt.event.KeyEvent evt) {                                       
        
        int lengthPIN = YearEXPDate.getText().length();
        
        if (lengthPIN == 4 ) {
            
            YearEXPDate.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 4 digits");
            
        }
        
    }                                      

    private void MonthUserEXPDateFKeyPressed(java.awt.event.KeyEvent evt) {                                             
        
        int lengthPIN = MonthUserEXPDateF.getText().length();
        
        if (lengthPIN == 2 ) {
            
            MonthUserEXPDateF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 2 digits");
            
        }
        
    }                                            

    private void DayEXPDateUserFKeyPressed(java.awt.event.KeyEvent evt) {                                           
        
        int lengthPIN = DayEXPDateUserF.getText().length();
        
        if (lengthPIN == 2 ) {
            
            DayEXPDateUserF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 2 digits");
            
        }
        
    }                                          

    private void UDOBLYearKeyTyped(java.awt.event.KeyEvent evt) {                                   
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                  

    private void UMonthDOBFKeyTyped(java.awt.event.KeyEvent evt) {                                    
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                   

    private void UDayDOBFKeyTyped(java.awt.event.KeyEvent evt) {                                  
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                 

    private void YearEXPDateKeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                    

    private void MonthUserEXPDateFKeyTyped(java.awt.event.KeyEvent evt) {                                           
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                          

    private void DayEXPDateUserFKeyTyped(java.awt.event.KeyEvent evt) {                                         
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        VehicleSafety.main(null);
        
    }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        jTextArea1.setText(null);
        LiveViewCBTN.setText("Live-View");
        
    }                                        

    private void VSIDKeyPressed(java.awt.event.KeyEvent evt) {                                
        
        int lengthPIN = VSID.getText().length();
        
        if (lengthPIN == 5 ) {
            
            VSID.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 5 digits");
            
        }
        
    }                               

    private void VSIDKeyTyped(java.awt.event.KeyEvent evt) {                              
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                evt.consume();

            }
            
    }                             

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        FQAForCustomers.main(null);
        
    }                                         

    private void UPhoneNoFActionPerformed(java.awt.event.ActionEvent evt) {                                          
      
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                         

    private void UPhoneNoFKeyPressed(java.awt.event.KeyEvent evt) {                                     
        
        int lengthPIN = UPhoneNoF.getText().length();
        
        if (lengthPIN == 14 ) {
            
            UPhoneNoF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 14 digits");
            
        }
        
    }                                    

    private void UPhoneNoFKeyTyped(java.awt.event.KeyEvent evt) {                                   
         
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                  

    private void UPasswordFKeyPressed(java.awt.event.KeyEvent evt) {                                      
        
        int lengthPIN = UPasswordF.getText().length();
        
        if (lengthPIN == 14 ) {
            
            UPasswordF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 14 digits");
            
        }
        
    }                                     

    private void UAddressFKeyPressed(java.awt.event.KeyEvent evt) {                                     
        
        int lengthPIN = UAddressF.getText().length();
        
        if (lengthPIN == 30 ) {
            
            UAddressF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 30 digits");
            
        }
    }                                    

    private void UERICodeFKeyPressed(java.awt.event.KeyEvent evt) {                                     
        
        int lengthPIN = UERICodeF.getText().length();
        
        if (lengthPIN == 8 ) {
            
            UERICodeF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 8 Char");
            
        }
    }                                    

    private void UserNameFKeyPressed(java.awt.event.KeyEvent evt) {                                     
        
        int lengthPIN = UserNameF.getText().length();
        
        if (lengthPIN == 14 ) {
            
            UserNameF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 14 Char");
            
        }
        
    }                                    

    private void UCCVBankCardFKeyPressed(java.awt.event.KeyEvent evt) {                                         
        
        int lengthPIN = UCCVBankCardF.getText().length();
        
        if (lengthPIN == 3 ) {
            
            UCCVBankCardF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 3 digits");
            
        }
        
    }                                        

    private void UCCVBankCardFActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                             

    private void UCardNOFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        JOptionPane.showMessageDialog(null, "Please, type numbers only!");
        
    }                                        

    private void UCardNOFKeyPressed(java.awt.event.KeyEvent evt) {                                    
        
        int lengthPIN = UCardNOF.getText().length();
        
        if (lengthPIN == 14 ) {
            
            UCardNOF.setText("");
           
            JOptionPane.showMessageDialog(null,"You cannot enter more than 14 digits");
            
        }
        
    }                                   

    private void UCCVBankCardFKeyTyped(java.awt.event.KeyEvent evt) {                                       
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                      

    private void UCardNOFKeyTyped(java.awt.event.KeyEvent evt) {                                  
        
        char c = evt.getKeyChar();
        
            if (!Character.isDigit(c)) {

                jLabel16.setVisible(true);
                evt.consume();

            }
            
            else {
                
                jLabel16.setVisible(false);
                
            }
            
    }                                 

    private void UserNameFKeyTyped(java.awt.event.KeyEvent evt) {                                   
        
        char c = evt.getKeyChar();
        
            if (Character.isDigit(c)) {

                evt.consume();

            }
            
    }                                  

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        System.exit(0);
        
    }                                        

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                               

        if (jToggleButton2.isSelected() == true){

            jLabel26.setVisible(false);
            jToggleButton2.setText("DarkMode");

        }

        else if (jToggleButton2.isSelected() == false) {

            jLabel26.setVisible(true);
            jToggleButton2.setText("LightMode");

        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public static javax.swing.JTextField DayEXPDateUserF;
    private javax.swing.JButton LiveViewCBTN;
    public static javax.swing.JTextField MonthUserEXPDateF;
    public static javax.swing.JTextField UAddressF;
    public static javax.swing.JTextField UCCVBankCardF;
    public static javax.swing.JLabel UCardEXPDateL;
    public static javax.swing.JTextField UCardNOF;
    public static javax.swing.JTextField UDOBLYear;
    public static javax.swing.JLabel UDOFL;
    public static javax.swing.JTextField UDayDOBF;
    public static javax.swing.JTextField UERICodeF;
    public static javax.swing.JTextField UIDF;
    public static javax.swing.JTextField UMonthDOBF;
    public static javax.swing.JPasswordField UPasswordF;
    public static javax.swing.JTextField UPhoneNoF;
    public static javax.swing.JButton UViewBTNInM;
    public static javax.swing.JTextField UserNameF;
    public static javax.swing.JTextField VSID;
    public static javax.swing.JTextField YearEXPDate;
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton10;
    public static javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextArea jTextArea3;
    public static javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JMenu time;
    // End of variables declaration                   
}
