/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author escan
 */
public class VehiclesInfo extends javax.swing.JFrame {

    /**
     * Creates new form VehiclesInfo
     */
    public VehiclesInfo() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }
    
    public void date() {
        
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(year + "/" + (month + 1) + "/" + day);
        
    }
    
    public void time() {
        
        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        time.setText(hour + ":" + minute + ":" + second);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The MAN is a German commercial vehicles manufacturer, renowned for its heavy-duty trucks and buses. The company is committed to providing reliable, customized solutions to fleet operators, from city buses to long-haul trucks. The MAN range of vehicles offers a variety of innovative solutions designed to meet the needs of every customer.\n\n\nThe Honda is a Japanese automotive manufacturer, offering a wide range of vehicles, ranging from cars and motorcycles to marine engines and power equipment. Honda is dedicated to providing customers with products that are reliable, efficient, and affordable. The company is renowned for its commitment to safety and innovation, with vehicles that include advanced features like airbags and blind spot monitoring.\n\n\nThe Mercedes is a German luxury car manufacturer, renowned for its high-end vehicles. Mercedes is known for its combination of luxury, performance, and safety, offering a range of vehicles that are comfortable and reliable. The company is committed to delivering the latest technology and features, such as adaptive cruise control and lane-keeping assistance, to provide a safe and enjoyable driving experience.\n\n\nThe Nissan is a Japanese automotive manufacturer, offering a range of vehicles from compact cars to SUVs and crossovers. Nissan is renowned for its reliable, efficient, and affordable range of vehicles. The company is committed to providing innovative solutions, such as driver-assistance systems and advanced safety technology, to ensure a safe and enjoyable driving experience.\n\nHonda offers a wide range of vehicles in a variety of sizes, colors, and capacities. The midsize vehicles are the most popular, with a range of 110 to 120 cubic feet and up to three rows of seating. The Honda Ridgeline, CR-V, Pilot, and Odyssey are all great options for towing and hauling, with the 2019 Honda models able to haul up to 5,000 pounds and tow up to 3,500 pounds [1,2,3]. Honda's electric vehicles have been designed with the environment in mind, making them an excellent choice for those looking to reduce their carbon footprint [1].\n\n\nReferences:\n[1] Honda Marks 30 Million Vehicle Production Milestone in the U.S.\n[2] Differences Between Subcompact, Compact, Midsize, and Full …\n[3] Honda Towing Capacity Guide - Honda of Jefferson City\n\n\nThe Mercedes-EQB is an all-electric compact SUV that offers space for many larger families and the most diverse transportation needs [1]. It is available in a range of colors, from classic black and white to vibrant blues and greens. The EQB has a length of 4.73 meters and a width of 1.88 meters, making it a compact and efficient SUV. The interior is spacious and comfortable, with two seats in the third row that can accommodate passengers up to 5 feet 4 inches tall [1]. It also offers plenty of cargo space, with a generous luggage compartment, as well as several storage compartments and cup holders. The EQB also offers a variety of drive systems and advanced technologies, such as Blind Spot Assist, Active Brake Assist, and Park Pilot [1].\n\n\nReferences:\n[1] The new EQB: family-size electric mobility - Mercedes-Benz USA\n[2] Mercedes-Benz C-Class vs. BMW 3-Series in Greenville, SC\n[3] First Class Finish| Mercedes-Benz | Madison | Middleton WI\n\n\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("All information here, do not hesitate to contact us to address your concerns ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiclesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiclesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiclesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiclesInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiclesInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu time;
    // End of variables declaration                   
}
