/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sql;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author escan
 */
public class VehicleSafety extends javax.swing.JFrame {

    /**
     * Creates new form VehicleSafety
     */
    public VehicleSafety() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        Timer timer;
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                time();
            }
        });
        timer.start();

        date();
    }
    
    public void date() {
        
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date.setText(year + "/" + (month + 1) + "/" + day);
        
    }
    
    public void time() {
        
        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        time.setText(hour + ":" + minute + ":" + second);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setTabSize(1);
        jTextArea1.setText("Safety\n\nVehicle safety is a crucial consideration when purchasing a car. In this day and age, cars are equipped with a variety of safety features and technologies aimed at reducing the risk of accidents and protecting drivers and passengers in the event of a collision. As a result, it is important to understand what these features and technologies are, how they work, and why they are important when selecting a vehicle.\n\nOne of the most important safety features in modern cars is the structure of the car itself. The design of the car's frame and body should be such that it is able to absorb and distribute energy from a collision, minimizing the risk of serious injury to the occupants. This is achieved through the use of crumple zones, which are areas of the car that are designed to deform during a collision, absorbing the energy of the impact and reducing the likelihood of serious injury.\n\nSeat belts and airbags are also critical components of modern vehicle safety. Seat belts keep passengers in place during a collision and reduce the risk of injury. Airbags, meanwhile, provide a cushioning effect during a collision and can reduce the severity of injuries. Many modern cars are now equipped with multiple airbags, including side airbags and even airbags built into the roof of the car to protect occupants in the event of a rollover.\n\nTechnology has also played a major role in improving vehicle safety. For example, anti-lock braking systems (ABS) are now standard in most vehicles, helping drivers to maintain control of their vehicles during sudden stops and reducing the risk of accidents. Electronic stability control (ESC) is another important technology, as it helps drivers to maintain control of their vehicles in difficult driving conditions, such as when driving on a slippery surface. Lane departure warning systems and blind-spot monitoring systems are also becoming increasingly common, helping drivers to avoid accidents caused by lane departures or by not seeing other vehicles.\n\nIn addition to these features, there are also a number of advanced driver-assist systems (ADAS) that can help to reduce the risk of accidents. For example, automatic emergency braking (AEB) systems can detect an imminent collision and automatically apply the brakes to reduce the impact of the collision or prevent it altogether. Adaptive cruise control (ACC) systems can help drivers to maintain a safe following distance, reducing the risk of rear-end collisions.\n\nRegulations also play a crucial role in ensuring vehicle safety. For example, regulations dictate the minimum safety requirements for vehicles, such as the use of seat belts, airbags, and anti-lock braking systems. Regulators also perform crash testing to determine how well vehicles perform in real-world collisions, providing important information to consumers about the safety of different vehicles. In some cases, regulators may even mandate the recall of vehicles that are found to be unsafe, in order to prevent accidents and protect consumers.\n\nWhen shopping for a car, it is important to consider the safety features and technologies that are available. For example, if you have a family, you may want to look for a vehicle with a high safety rating and a number of airbags, in order to provide the greatest protection for your passengers. On the other hand, if you are looking for a car for commuting, you may be more interested in features such as advanced driver-assist systems and anti-lock braking systems, which can help you avoid accidents and drive more confidently.\n\nIt is also important to consider your driving habits when selecting a vehicle. For example, if you frequently drive in heavy traffic or on winding roads, you may want to look for a car with a high level of stability control and lane departure warning systems, in order to help you avoid accidents and drive with confidence. ");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SAFETY", jPanel1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Performance\n\nPerformance is a critical consideration when purchasing a vehicle. Performance refers to a car's ability to accelerate, handle, and respond to the driver's inputs, which are important factors in determining driving enjoyment and overall satisfaction. When shopping for a vehicle, it is important to understand the different aspects of performance, and to consider your own driving needs and preferences.\n\nAcceleration is an important aspect of performance, and is determined by the power and torque of the engine, as well as the vehicle's weight and aerodynamics. A car with a high-powered engine and low weight will generally accelerate faster than a car with a less powerful engine and a heavier weight. When shopping for a vehicle, it is important to consider the type of driving you will be doing, and to select a car that has an appropriate level of acceleration for your needs.\n\nHandling is another important aspect of performance. This refers to a car's ability to turn and maneuver around corners, and is determined by factors such as suspension design, tire type, and weight distribution. A car with a well-designed suspension and a balanced weight distribution will generally handle better than a car with a poorly designed suspension or an unbalanced weight distribution. When shopping for a vehicle, it is important to consider the type of driving you will be doing, and to select a car that has an appropriate level of handling for your needs.\n\nResponsiveness is also an important aspect of performance, and refers to the car's ability to respond to the driver's inputs. This includes factors such as steering feel and brake responsiveness, as well as the overall feel of the car when driving. A car with a well-designed steering system and brakes that provide good feedback and stopping power will generally be more responsive and easier to drive than a car with a poorly designed steering system and brakes that are less responsive.\n\nIn addition to these aspects of performance, it is also important to consider factors such as fuel efficiency, reliability, and maintenance costs. A car that provides good performance may not be the best choice if it has poor fuel efficiency, is unreliable, or is expensive to maintain. On the other hand, a car that provides good fuel efficiency, reliability, and low maintenance costs may not be the best choice if it has poor performance.\n\nWhen shopping for a vehicle, it is important to consider your own driving needs and preferences. If you are looking for a car for daily commuting, for example, you may be more interested in fuel efficiency and reliability than in performance. On the other hand, if you are looking for a car for weekend driving or track days, you may be more interested in acceleration, handling, and responsiveness.\n\nUltimately, the best way to determine which vehicle is right for you is to test drive a number of different cars and to compare their performance in real-world driving conditions. This will give you a sense of the car's acceleration, handling, and responsiveness, as well as its fuel efficiency, reliability, and maintenance costs, and will help you to make an informed decision when purchasing a vehicle.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PERFORMANCE", jPanel2);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Evaluation\n\nEvaluation is an important step in the process of purchasing a vehicle, as it helps you to determine whether a particular vehicle is the right choice for your needs. There are several different aspects of a vehicle that you should evaluate when shopping for a car, including performance, safety, comfort, and reliability.\n\nPerformance evaluation is important in determining whether a vehicle can meet your driving needs and preferences. This includes evaluating the car's acceleration, handling, and responsiveness, as well as its fuel efficiency, reliability, and maintenance costs. When evaluating performance, it is important to consider how the car will perform in real-world driving conditions, rather than relying solely on manufacturer specifications or test results.\n\nSafety evaluation is also important, as it helps you to determine whether a vehicle can provide a safe driving experience. This includes evaluating the car's crash test ratings, as well as its safety features, such as airbags, anti-lock brakes, and stability control. When evaluating safety, it is also important to consider factors such as visibility and ease of use of the car's controls, as these can also affect your overall safety on the road.\n\nComfort evaluation is important in determining whether a vehicle can provide a comfortable driving experience. This includes evaluating factors such as the car's interior design, seat comfort, and climate control. When evaluating comfort, it is important to consider the type of driving you will be doing, as well as your personal preferences, such as whether you prefer a quiet or sporty driving experience.\n\nReliability evaluation is important in determining whether a vehicle can provide reliable and long-lasting performance. This includes evaluating factors such as the car's maintenance schedule, as well as its warranty and service support. When evaluating reliability, it is important to consider both the manufacturer's reputation and your own experiences with the car or similar vehicles.\n\nIn addition to these aspects of evaluation, it is also important to consider factors such as cost and value, as well as your own personal preferences and lifestyle. For example, if you are looking for a car for daily commuting, you may be more interested in fuel efficiency and reliability, whereas if you are looking for a car for weekend driving or track days, you may be more interested in performance.\n\nUltimately, the best way to evaluate a vehicle is to test drive a number of different cars and to compare their performance, safety, comfort, and reliability in real-world driving conditions. This will help you to make an informed decision when purchasing a vehicle, and will give you a sense of which car is the right choice for your needs.");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EVALUATION", jPanel3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAESRESOURCES/VNO1.jpg"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        jButton2.setText("More images");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/job.png"))); // NOI18N
        jButton3.setText("Vehicle's info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("IMAGES", jPanel4);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Vehicle Purchase application by Eskandar Atrakchi Terms & Conditions:\n\nWelcome to our vehicle purchase website, where you can find and purchase the car of your dreams. Our website offers a variety of vehicles from different makes, models, and years, all sourced from trusted sellers. We strive to provide our customers with an enjoyable and hassle-free shopping experience. To ensure a smooth transaction, please take the time to read through our terms and conditions before making any purchases.\n\nBy accessing and using our website, you agree to be bound by these terms and conditions. If you do not agree to these terms and conditions, you should not use our website. We reserve the right to modify these terms and conditions at any time, so please check back periodically. Your continued use of our website following any changes indicates your acceptance of the new terms and conditions.\n\nThe descriptions of the vehicles listed on our website are based on information provided by the sellers. While we do our best to verify the accuracy of this information, we cannot guarantee its accuracy and make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose.\n\nTo purchase a vehicle, you must follow the instructions on the website and provide the required information. The purchase price for the vehicle, including any applicable taxes and fees, will be indicated on the website and must be paid in full before the vehicle can be shipped to you. We accept various forms of payment, including credit cards and PayPal. All transactions are processed through a secure payment gateway to protect your personal and financial information.\n\nOnce you have made a purchase, you will receive a confirmation email that includes the details of your transaction. You will also receive a tracking number for your shipment once it has been dispatched. Please allow sufficient time for delivery, which will depend on your location and the shipping method you have chosen.\n\nIf you encounter any issues with your purchase or shipment, please contact us immediately and we will do our best to resolve the matter as quickly as possible. If you are not satisfied with your purchase, you may be eligible for a return or exchange, subject to our return policy. Our return policy is available on the website and outlines the steps you need to follow to initiate a return or exchange.\n\nWe hope you have a positive experience using our vehicle purchase website. If you have any questions or concerns, please do not hesitate to contact us. Our customer service team is available to assist you Monday to Friday, from 9 am to 5 pm EST.\n\nBy using our website and making a purchase, you agree to be bound by these terms and conditions. Thank you for choosing our vehicle purchase website, and we look forward to helping you find your dream car.");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TERMS & CONDITIONS", jPanel5);

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
        IMG1.main(null);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        VehiclesInfo.main(null);
        this.dispose();
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleSafety.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleSafety.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleSafety.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleSafety.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleSafety().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JMenu time;
    // End of variables declaration                   
}
